messages:
  command-sender-is-not-player:
    enabled: true
    message:
      - "This command can only be entered by a player."
  rules-command-you-don't-have-permission:
    enabled: true
    message:
      - "You don't have permission."
  rules-command-successfully:
    enabled: true
    message:
      - "These are the rules of our server"


title: "Rules"
author: "August1251"
rules:
  1:
    - "1.1 Test"
    - "1.2 Test"
    - "1.3 Test"
  2:
    - "2.1 Test"
    - "2.2 Test"
    - "2.3 Test"